// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Importar todas tus fuentes personalizadas
import {
  appetiteProBold,
  appetiteProHeavy,
  appetiteProMedium,
  quicksandBold,
  quicksandMedium,
  quicksandRegular,
  quicksandSemiBold,
} from "@/lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Distrito Dulce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} 
        ${appetiteProBold.variable} 
        ${appetiteProHeavy.variable} 
        ${appetiteProMedium.variable}
        ${quicksandBold.variable}
        ${quicksandMedium.variable}
        ${quicksandRegular.variable}
        ${quicksandSemiBold.variable}
      `}
    >
      <body className={quicksandRegular.className}>{children}</body>
    </html>
  );
}
